# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
deploy:
  provider: pages
  skip-cleanup: true
  github-toker: $GITHUB_PUSH_KEY
  keep-history: true
  target-branch: build
  verbose: true
  on:
    branch: master