# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
after_success:
  - Rscript -e 'cov
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PUSH_KEY
  keep-history: true
  target-branch: build
  verbose: true
  on:
    branch: master