// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ProcessFreq
NumericVector ProcessFreq(DataFrame variant, std::vector<bool> absolute, bool totals, bool genotypic, bool allelic, bool percentage, bool extrapolateFreq, double minFreqAl, double minFreqGt);
RcppExport SEXP _rsurvival_ProcessFreq(SEXP variantSEXP, SEXP absoluteSEXP, SEXP totalsSEXP, SEXP genotypicSEXP, SEXP allelicSEXP, SEXP percentageSEXP, SEXP extrapolateFreqSEXP, SEXP minFreqAlSEXP, SEXP minFreqGtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type variant(variantSEXP);
    Rcpp::traits::input_parameter< std::vector<bool> >::type absolute(absoluteSEXP);
    Rcpp::traits::input_parameter< bool >::type totals(totalsSEXP);
    Rcpp::traits::input_parameter< bool >::type genotypic(genotypicSEXP);
    Rcpp::traits::input_parameter< bool >::type allelic(allelicSEXP);
    Rcpp::traits::input_parameter< bool >::type percentage(percentageSEXP);
    Rcpp::traits::input_parameter< bool >::type extrapolateFreq(extrapolateFreqSEXP);
    Rcpp::traits::input_parameter< double >::type minFreqAl(minFreqAlSEXP);
    Rcpp::traits::input_parameter< double >::type minFreqGt(minFreqGtSEXP);
    rcpp_result_gen = Rcpp::wrap(ProcessFreq(variant, absolute, totals, genotypic, allelic, percentage, extrapolateFreq, minFreqAl, minFreqGt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rsurvival_ProcessFreq", (DL_FUNC) &_rsurvival_ProcessFreq, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_rsurvival(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
