# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ProcessFreq <- function(variant, absolute, totals = TRUE, genotypic = TRUE, allelic = FALSE, percentage = FALSE, extrapolateFreq = TRUE, minFreqAl = -1, minFreqGt = -1) {
    .Call('_rsurvival_ProcessFreq', PACKAGE = 'rsurvival', variant, absolute, totals, genotypic, allelic, percentage, extrapolateFreq, minFreqAl, minFreqGt)
}

