# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ShapeCountsCpp <- function(counts, absolute, totals = TRUE, genotypic = TRUE, allelic = FALSE, percentage = FALSE, extrapolateFreq = TRUE, minFreqAl = -1, minFreqGt = -1) {
    .Call('_rsurvival_ShapeCountsCpp', PACKAGE = 'rsurvival', counts, absolute, totals, genotypic, allelic, percentage, extrapolateFreq, minFreqAl, minFreqGt)
}

CheapDataFrameBuilder <- function(a) {
    .Call('_rsurvival_CheapDataFrameBuilder', PACKAGE = 'rsurvival', a)
}

CalcFreqCpp <- function(gt, absolute, totals = TRUE, genotypic = TRUE, allelic = FALSE, percentage = FALSE, extrapolateFreq = TRUE, minFreqAl = -1, minFreqGt = -1) {
    .Call('_rsurvival_CalcFreqCpp', PACKAGE = 'rsurvival', gt, absolute, totals, genotypic, allelic, percentage, extrapolateFreq, minFreqAl, minFreqGt)
}

CalcProbCpp <- function(counts, absolute, totals = TRUE, genotypic = TRUE, allelic = FALSE, percentage = FALSE, extrapolateFreq = TRUE, minFreqAl = -1, minFreqGt = -1) {
    .Call('_rsurvival_CalcProbCpp', PACKAGE = 'rsurvival', counts, absolute, totals, genotypic, allelic, percentage, extrapolateFreq, minFreqAl, minFreqGt)
}

